# Generated by Django 5.2.8 on 2026-06-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_orderitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Shoes', 'Shoes'), ('Watch', 'Watch'), ('Laptop', 'Laptop'), ('Phone', 'Phone'), ('Accessories', 'Accessories')], default='Electronics', max_length=100),
        ),
    ]
